### ISSUE TITLE
Alias variables

### ISSUE THREAD

**Issue by mtfd** [dustin638/Mirabell#8]
Add a variable processing system within the aliases using curl braces to denote a variable.

The alias system should support these variables:
```
{0} - A string passed after the alias
{prev} - The previous person to speak in the channel
{rand} - A random user in the channel
````

**Comment by dustin638** [comment]
Another alias feature that would be nice is to be able to add/remove aliases by querying the bot if you're admin, rather than doing it in this channel or having to use sqlite in the terminal.
